services:
    web:
        platform: linux/amd64 # Explicitly set for TDX
        image: pivortex/based-agent-template:latest@sha256:454b15b8b87ab45e91d8e7ab8b820ff3b1aca2a1fe91c8104c690ec84c213f73
        container_name: web
        ports:
            - '3000:3000'
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
        restart: always
