services:
    web:
        platform: linux/amd64 # Explicitly set for TDX
        image: pivortex/based-agent-template:latest@sha256:62c5877a9abef103c74f8b6f269110ff957c59e7e51b42dbc09e1362ecc7b34c
        container_name: web
        ports:
            - '3000:3000'
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
        restart: always
