services:
    web:
        platform: linux/amd64 # Explicitly set for TDX
        image: pivortex/based-agent-template:latest@sha256:d56cb5543d597388100dd9a3e7ced2c7d7ebacb4cda13e38bf7a6d71b97a77b0
        container_name: web
        ports:
            - '3000:3000'
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
        restart: always
